dir: "{{.InterfaceDir}}"
structname: "{{.InterfaceName}}Mock"
filename: "{{.InterfaceName | lower}}_test.go"
pkgname: "{{.SrcPackageName}}"
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/mbretter/go-mongodb-queue/v3:
    interfaces:
      DbInterface:
      ChangeStreamInterface:
      CollectionInterface:
