// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queue

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewChangeStreamInterfaceMock creates a new instance of ChangeStreamInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChangeStreamInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChangeStreamInterfaceMock {
	mock := &ChangeStreamInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ChangeStreamInterfaceMock is an autogenerated mock type for the ChangeStreamInterface type
type ChangeStreamInterfaceMock struct {
	mock.Mock
}

type ChangeStreamInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ChangeStreamInterfaceMock) EXPECT() *ChangeStreamInterfaceMock_Expecter {
	return &ChangeStreamInterfaceMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type ChangeStreamInterfaceMock
func (_mock *ChangeStreamInterfaceMock) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ChangeStreamInterfaceMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ChangeStreamInterfaceMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ChangeStreamInterfaceMock_Expecter) Close(ctx any) *ChangeStreamInterfaceMock_Close_Call {
	return &ChangeStreamInterfaceMock_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *ChangeStreamInterfaceMock_Close_Call) Run(run func(ctx context.Context)) *ChangeStreamInterfaceMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ChangeStreamInterfaceMock_Close_Call) Return(err error) *ChangeStreamInterfaceMock_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ChangeStreamInterfaceMock_Close_Call) RunAndReturn(run func(ctx context.Context) error) *ChangeStreamInterfaceMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Decode provides a mock function for the type ChangeStreamInterfaceMock
func (_mock *ChangeStreamInterfaceMock) Decode(v any) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ChangeStreamInterfaceMock_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type ChangeStreamInterfaceMock_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - v any
func (_e *ChangeStreamInterfaceMock_Expecter) Decode(v any) *ChangeStreamInterfaceMock_Decode_Call {
	return &ChangeStreamInterfaceMock_Decode_Call{Call: _e.mock.On("Decode", v)}
}

func (_c *ChangeStreamInterfaceMock_Decode_Call) Run(run func(v any)) *ChangeStreamInterfaceMock_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ChangeStreamInterfaceMock_Decode_Call) Return(err error) *ChangeStreamInterfaceMock_Decode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ChangeStreamInterfaceMock_Decode_Call) RunAndReturn(run func(v any) error) *ChangeStreamInterfaceMock_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type ChangeStreamInterfaceMock
func (_mock *ChangeStreamInterfaceMock) Next(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ChangeStreamInterfaceMock_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type ChangeStreamInterfaceMock_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ChangeStreamInterfaceMock_Expecter) Next(ctx any) *ChangeStreamInterfaceMock_Next_Call {
	return &ChangeStreamInterfaceMock_Next_Call{Call: _e.mock.On("Next", ctx)}
}

func (_c *ChangeStreamInterfaceMock_Next_Call) Run(run func(ctx context.Context)) *ChangeStreamInterfaceMock_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ChangeStreamInterfaceMock_Next_Call) Return(b bool) *ChangeStreamInterfaceMock_Next_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ChangeStreamInterfaceMock_Next_Call) RunAndReturn(run func(ctx context.Context) bool) *ChangeStreamInterfaceMock_Next_Call {
	_c.Call.Return(run)
	return _c
}
