// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queue

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// NewCollectionInterfaceMock creates a new instance of CollectionInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollectionInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CollectionInterfaceMock {
	mock := &CollectionInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CollectionInterfaceMock is an autogenerated mock type for the CollectionInterface type
type CollectionInterfaceMock struct {
	mock.Mock
}

type CollectionInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CollectionInterfaceMock) EXPECT() *CollectionInterfaceMock_Expecter {
	return &CollectionInterfaceMock_Expecter{mock: &_m.Mock}
}

// FindOneAndUpdate provides a mock function for the type CollectionInterfaceMock
func (_mock *CollectionInterfaceMock) FindOneAndUpdate(ctx context.Context, filter any, update any, opts ...options.Lister[options.FindOneAndUpdateOptions]) *mongo.SingleResult {
	// options.Lister[options.FindOneAndUpdateOptions]
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, filter, update)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndUpdate")
	}

	var r0 *mongo.SingleResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any, ...options.Lister[options.FindOneAndUpdateOptions]) *mongo.SingleResult); ok {
		r0 = returnFunc(ctx, filter, update, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.SingleResult)
		}
	}
	return r0
}

// CollectionInterfaceMock_FindOneAndUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneAndUpdate'
type CollectionInterfaceMock_FindOneAndUpdate_Call struct {
	*mock.Call
}

// FindOneAndUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - update any
//   - opts ...options.Lister[options.FindOneAndUpdateOptions]
func (_e *CollectionInterfaceMock_Expecter) FindOneAndUpdate(ctx any, filter any, update any, opts ...any) *CollectionInterfaceMock_FindOneAndUpdate_Call {
	return &CollectionInterfaceMock_FindOneAndUpdate_Call{Call: _e.mock.On("FindOneAndUpdate",
		append([]any{ctx, filter, update}, opts...)...)}
}

func (_c *CollectionInterfaceMock_FindOneAndUpdate_Call) Run(run func(ctx context.Context, filter any, update any, opts ...options.Lister[options.FindOneAndUpdateOptions])) *CollectionInterfaceMock_FindOneAndUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []options.Lister[options.FindOneAndUpdateOptions]
		variadicArgs := make([]options.Lister[options.FindOneAndUpdateOptions], len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(options.Lister[options.FindOneAndUpdateOptions])
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *CollectionInterfaceMock_FindOneAndUpdate_Call) Return(singleResult *mongo.SingleResult) *CollectionInterfaceMock_FindOneAndUpdate_Call {
	_c.Call.Return(singleResult)
	return _c
}

func (_c *CollectionInterfaceMock_FindOneAndUpdate_Call) RunAndReturn(run func(ctx context.Context, filter any, update any, opts ...options.Lister[options.FindOneAndUpdateOptions]) *mongo.SingleResult) *CollectionInterfaceMock_FindOneAndUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Indexes provides a mock function for the type CollectionInterfaceMock
func (_mock *CollectionInterfaceMock) Indexes() mongo.IndexView {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Indexes")
	}

	var r0 mongo.IndexView
	if returnFunc, ok := ret.Get(0).(func() mongo.IndexView); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(mongo.IndexView)
	}
	return r0
}

// CollectionInterfaceMock_Indexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Indexes'
type CollectionInterfaceMock_Indexes_Call struct {
	*mock.Call
}

// Indexes is a helper method to define mock.On call
func (_e *CollectionInterfaceMock_Expecter) Indexes() *CollectionInterfaceMock_Indexes_Call {
	return &CollectionInterfaceMock_Indexes_Call{Call: _e.mock.On("Indexes")}
}

func (_c *CollectionInterfaceMock_Indexes_Call) Run(run func()) *CollectionInterfaceMock_Indexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CollectionInterfaceMock_Indexes_Call) Return(indexView mongo.IndexView) *CollectionInterfaceMock_Indexes_Call {
	_c.Call.Return(indexView)
	return _c
}

func (_c *CollectionInterfaceMock_Indexes_Call) RunAndReturn(run func() mongo.IndexView) *CollectionInterfaceMock_Indexes_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOne provides a mock function for the type CollectionInterfaceMock
func (_mock *CollectionInterfaceMock) InsertOne(ctx context.Context, document any, opts ...options.Lister[options.InsertOneOptions]) (*mongo.InsertOneResult, error) {
	// options.Lister[options.InsertOneOptions]
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, document)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for InsertOne")
	}

	var r0 *mongo.InsertOneResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...options.Lister[options.InsertOneOptions]) (*mongo.InsertOneResult, error)); ok {
		return returnFunc(ctx, document, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...options.Lister[options.InsertOneOptions]) *mongo.InsertOneResult); ok {
		r0 = returnFunc(ctx, document, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.InsertOneResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any, ...options.Lister[options.InsertOneOptions]) error); ok {
		r1 = returnFunc(ctx, document, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CollectionInterfaceMock_InsertOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOne'
type CollectionInterfaceMock_InsertOne_Call struct {
	*mock.Call
}

// InsertOne is a helper method to define mock.On call
//   - ctx context.Context
//   - document any
//   - opts ...options.Lister[options.InsertOneOptions]
func (_e *CollectionInterfaceMock_Expecter) InsertOne(ctx any, document any, opts ...any) *CollectionInterfaceMock_InsertOne_Call {
	return &CollectionInterfaceMock_InsertOne_Call{Call: _e.mock.On("InsertOne",
		append([]any{ctx, document}, opts...)...)}
}

func (_c *CollectionInterfaceMock_InsertOne_Call) Run(run func(ctx context.Context, document any, opts ...options.Lister[options.InsertOneOptions])) *CollectionInterfaceMock_InsertOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []options.Lister[options.InsertOneOptions]
		variadicArgs := make([]options.Lister[options.InsertOneOptions], len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(options.Lister[options.InsertOneOptions])
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CollectionInterfaceMock_InsertOne_Call) Return(res *mongo.InsertOneResult, err error) *CollectionInterfaceMock_InsertOne_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *CollectionInterfaceMock_InsertOne_Call) RunAndReturn(run func(ctx context.Context, document any, opts ...options.Lister[options.InsertOneOptions]) (*mongo.InsertOneResult, error)) *CollectionInterfaceMock_InsertOne_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMany provides a mock function for the type CollectionInterfaceMock
func (_mock *CollectionInterfaceMock) UpdateMany(ctx context.Context, filter any, update any, opts ...options.Lister[options.UpdateManyOptions]) (*mongo.UpdateResult, error) {
	// options.Lister[options.UpdateManyOptions]
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, filter, update)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMany")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any, ...options.Lister[options.UpdateManyOptions]) (*mongo.UpdateResult, error)); ok {
		return returnFunc(ctx, filter, update, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any, ...options.Lister[options.UpdateManyOptions]) *mongo.UpdateResult); ok {
		r0 = returnFunc(ctx, filter, update, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any, any, ...options.Lister[options.UpdateManyOptions]) error); ok {
		r1 = returnFunc(ctx, filter, update, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CollectionInterfaceMock_UpdateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMany'
type CollectionInterfaceMock_UpdateMany_Call struct {
	*mock.Call
}

// UpdateMany is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - update any
//   - opts ...options.Lister[options.UpdateManyOptions]
func (_e *CollectionInterfaceMock_Expecter) UpdateMany(ctx any, filter any, update any, opts ...any) *CollectionInterfaceMock_UpdateMany_Call {
	return &CollectionInterfaceMock_UpdateMany_Call{Call: _e.mock.On("UpdateMany",
		append([]any{ctx, filter, update}, opts...)...)}
}

func (_c *CollectionInterfaceMock_UpdateMany_Call) Run(run func(ctx context.Context, filter any, update any, opts ...options.Lister[options.UpdateManyOptions])) *CollectionInterfaceMock_UpdateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []options.Lister[options.UpdateManyOptions]
		variadicArgs := make([]options.Lister[options.UpdateManyOptions], len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(options.Lister[options.UpdateManyOptions])
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *CollectionInterfaceMock_UpdateMany_Call) Return(res *mongo.UpdateResult, err error) *CollectionInterfaceMock_UpdateMany_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *CollectionInterfaceMock_UpdateMany_Call) RunAndReturn(run func(ctx context.Context, filter any, update any, opts ...options.Lister[options.UpdateManyOptions]) (*mongo.UpdateResult, error)) *CollectionInterfaceMock_UpdateMany_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOne provides a mock function for the type CollectionInterfaceMock
func (_mock *CollectionInterfaceMock) UpdateOne(ctx context.Context, filter any, update any, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
	// options.Lister[options.UpdateOneOptions]
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, filter, update)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOne")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any, ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error)); ok {
		return returnFunc(ctx, filter, update, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any, ...options.Lister[options.UpdateOneOptions]) *mongo.UpdateResult); ok {
		r0 = returnFunc(ctx, filter, update, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any, any, ...options.Lister[options.UpdateOneOptions]) error); ok {
		r1 = returnFunc(ctx, filter, update, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CollectionInterfaceMock_UpdateOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOne'
type CollectionInterfaceMock_UpdateOne_Call struct {
	*mock.Call
}

// UpdateOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - update any
//   - opts ...options.Lister[options.UpdateOneOptions]
func (_e *CollectionInterfaceMock_Expecter) UpdateOne(ctx any, filter any, update any, opts ...any) *CollectionInterfaceMock_UpdateOne_Call {
	return &CollectionInterfaceMock_UpdateOne_Call{Call: _e.mock.On("UpdateOne",
		append([]any{ctx, filter, update}, opts...)...)}
}

func (_c *CollectionInterfaceMock_UpdateOne_Call) Run(run func(ctx context.Context, filter any, update any, opts ...options.Lister[options.UpdateOneOptions])) *CollectionInterfaceMock_UpdateOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []options.Lister[options.UpdateOneOptions]
		variadicArgs := make([]options.Lister[options.UpdateOneOptions], len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(options.Lister[options.UpdateOneOptions])
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *CollectionInterfaceMock_UpdateOne_Call) Return(res *mongo.UpdateResult, err error) *CollectionInterfaceMock_UpdateOne_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *CollectionInterfaceMock_UpdateOne_Call) RunAndReturn(run func(ctx context.Context, filter any, update any, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error)) *CollectionInterfaceMock_UpdateOne_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type CollectionInterfaceMock
func (_mock *CollectionInterfaceMock) Watch(ctx context.Context, pipeline any, opts ...options.Lister[options.ChangeStreamOptions]) (*mongo.ChangeStream, error) {
	// options.Lister[options.ChangeStreamOptions]
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, pipeline)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 *mongo.ChangeStream
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...options.Lister[options.ChangeStreamOptions]) (*mongo.ChangeStream, error)); ok {
		return returnFunc(ctx, pipeline, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...options.Lister[options.ChangeStreamOptions]) *mongo.ChangeStream); ok {
		r0 = returnFunc(ctx, pipeline, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.ChangeStream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any, ...options.Lister[options.ChangeStreamOptions]) error); ok {
		r1 = returnFunc(ctx, pipeline, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CollectionInterfaceMock_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type CollectionInterfaceMock_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - pipeline any
//   - opts ...options.Lister[options.ChangeStreamOptions]
func (_e *CollectionInterfaceMock_Expecter) Watch(ctx any, pipeline any, opts ...any) *CollectionInterfaceMock_Watch_Call {
	return &CollectionInterfaceMock_Watch_Call{Call: _e.mock.On("Watch",
		append([]any{ctx, pipeline}, opts...)...)}
}

func (_c *CollectionInterfaceMock_Watch_Call) Run(run func(ctx context.Context, pipeline any, opts ...options.Lister[options.ChangeStreamOptions])) *CollectionInterfaceMock_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []options.Lister[options.ChangeStreamOptions]
		variadicArgs := make([]options.Lister[options.ChangeStreamOptions], len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(options.Lister[options.ChangeStreamOptions])
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CollectionInterfaceMock_Watch_Call) Return(stream *mongo.ChangeStream, err error) *CollectionInterfaceMock_Watch_Call {
	_c.Call.Return(stream, err)
	return _c
}

func (_c *CollectionInterfaceMock_Watch_Call) RunAndReturn(run func(ctx context.Context, pipeline any, opts ...options.Lister[options.ChangeStreamOptions]) (*mongo.ChangeStream, error)) *CollectionInterfaceMock_Watch_Call {
	_c.Call.Return(run)
	return _c
}
