// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queue

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// NewDbInterfaceMock creates a new instance of DbInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDbInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DbInterfaceMock {
	mock := &DbInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DbInterfaceMock is an autogenerated mock type for the DbInterface type
type DbInterfaceMock struct {
	mock.Mock
}

type DbInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DbInterfaceMock) EXPECT() *DbInterfaceMock_Expecter {
	return &DbInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateIndexes provides a mock function for the type DbInterfaceMock
func (_mock *DbInterfaceMock) CreateIndexes(ctx context.Context, index []mongo.IndexModel) error {
	ret := _mock.Called(ctx, index)

	if len(ret) == 0 {
		panic("no return value specified for CreateIndexes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []mongo.IndexModel) error); ok {
		r0 = returnFunc(ctx, index)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DbInterfaceMock_CreateIndexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIndexes'
type DbInterfaceMock_CreateIndexes_Call struct {
	*mock.Call
}

// CreateIndexes is a helper method to define mock.On call
//   - ctx context.Context
//   - index []mongo.IndexModel
func (_e *DbInterfaceMock_Expecter) CreateIndexes(ctx any, index any) *DbInterfaceMock_CreateIndexes_Call {
	return &DbInterfaceMock_CreateIndexes_Call{Call: _e.mock.On("CreateIndexes", ctx, index)}
}

func (_c *DbInterfaceMock_CreateIndexes_Call) Run(run func(ctx context.Context, index []mongo.IndexModel)) *DbInterfaceMock_CreateIndexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []mongo.IndexModel
		if args[1] != nil {
			arg1 = args[1].([]mongo.IndexModel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DbInterfaceMock_CreateIndexes_Call) Return(err error) *DbInterfaceMock_CreateIndexes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DbInterfaceMock_CreateIndexes_Call) RunAndReturn(run func(ctx context.Context, index []mongo.IndexModel) error) *DbInterfaceMock_CreateIndexes_Call {
	_c.Call.Return(run)
	return _c
}

// FindOneAndUpdate provides a mock function for the type DbInterfaceMock
func (_mock *DbInterfaceMock) FindOneAndUpdate(ctx context.Context, filter any, update any, opts ...options.Lister[options.FindOneAndUpdateOptions]) *mongo.SingleResult {
	// options.Lister[options.FindOneAndUpdateOptions]
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, filter, update)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndUpdate")
	}

	var r0 *mongo.SingleResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any, ...options.Lister[options.FindOneAndUpdateOptions]) *mongo.SingleResult); ok {
		r0 = returnFunc(ctx, filter, update, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.SingleResult)
		}
	}
	return r0
}

// DbInterfaceMock_FindOneAndUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneAndUpdate'
type DbInterfaceMock_FindOneAndUpdate_Call struct {
	*mock.Call
}

// FindOneAndUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - update any
//   - opts ...options.Lister[options.FindOneAndUpdateOptions]
func (_e *DbInterfaceMock_Expecter) FindOneAndUpdate(ctx any, filter any, update any, opts ...any) *DbInterfaceMock_FindOneAndUpdate_Call {
	return &DbInterfaceMock_FindOneAndUpdate_Call{Call: _e.mock.On("FindOneAndUpdate",
		append([]any{ctx, filter, update}, opts...)...)}
}

func (_c *DbInterfaceMock_FindOneAndUpdate_Call) Run(run func(ctx context.Context, filter any, update any, opts ...options.Lister[options.FindOneAndUpdateOptions])) *DbInterfaceMock_FindOneAndUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []options.Lister[options.FindOneAndUpdateOptions]
		variadicArgs := make([]options.Lister[options.FindOneAndUpdateOptions], len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(options.Lister[options.FindOneAndUpdateOptions])
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *DbInterfaceMock_FindOneAndUpdate_Call) Return(singleResult *mongo.SingleResult) *DbInterfaceMock_FindOneAndUpdate_Call {
	_c.Call.Return(singleResult)
	return _c
}

func (_c *DbInterfaceMock_FindOneAndUpdate_Call) RunAndReturn(run func(ctx context.Context, filter any, update any, opts ...options.Lister[options.FindOneAndUpdateOptions]) *mongo.SingleResult) *DbInterfaceMock_FindOneAndUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOne provides a mock function for the type DbInterfaceMock
func (_mock *DbInterfaceMock) InsertOne(ctx context.Context, document any) (bson.ObjectID, error) {
	ret := _mock.Called(ctx, document)

	if len(ret) == 0 {
		panic("no return value specified for InsertOne")
	}

	var r0 bson.ObjectID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) (bson.ObjectID, error)); ok {
		return returnFunc(ctx, document)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) bson.ObjectID); ok {
		r0 = returnFunc(ctx, document)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bson.ObjectID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any) error); ok {
		r1 = returnFunc(ctx, document)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DbInterfaceMock_InsertOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOne'
type DbInterfaceMock_InsertOne_Call struct {
	*mock.Call
}

// InsertOne is a helper method to define mock.On call
//   - ctx context.Context
//   - document any
func (_e *DbInterfaceMock_Expecter) InsertOne(ctx any, document any) *DbInterfaceMock_InsertOne_Call {
	return &DbInterfaceMock_InsertOne_Call{Call: _e.mock.On("InsertOne", ctx, document)}
}

func (_c *DbInterfaceMock_InsertOne_Call) Run(run func(ctx context.Context, document any)) *DbInterfaceMock_InsertOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DbInterfaceMock_InsertOne_Call) Return(objectID bson.ObjectID, err error) *DbInterfaceMock_InsertOne_Call {
	_c.Call.Return(objectID, err)
	return _c
}

func (_c *DbInterfaceMock_InsertOne_Call) RunAndReturn(run func(ctx context.Context, document any) (bson.ObjectID, error)) *DbInterfaceMock_InsertOne_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMany provides a mock function for the type DbInterfaceMock
func (_mock *DbInterfaceMock) UpdateMany(ctx context.Context, filter any, update any) error {
	ret := _mock.Called(ctx, filter, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any) error); ok {
		r0 = returnFunc(ctx, filter, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DbInterfaceMock_UpdateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMany'
type DbInterfaceMock_UpdateMany_Call struct {
	*mock.Call
}

// UpdateMany is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - update any
func (_e *DbInterfaceMock_Expecter) UpdateMany(ctx any, filter any, update any) *DbInterfaceMock_UpdateMany_Call {
	return &DbInterfaceMock_UpdateMany_Call{Call: _e.mock.On("UpdateMany", ctx, filter, update)}
}

func (_c *DbInterfaceMock_UpdateMany_Call) Run(run func(ctx context.Context, filter any, update any)) *DbInterfaceMock_UpdateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DbInterfaceMock_UpdateMany_Call) Return(err error) *DbInterfaceMock_UpdateMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DbInterfaceMock_UpdateMany_Call) RunAndReturn(run func(ctx context.Context, filter any, update any) error) *DbInterfaceMock_UpdateMany_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOne provides a mock function for the type DbInterfaceMock
func (_mock *DbInterfaceMock) UpdateOne(ctx context.Context, filter any, update any) error {
	ret := _mock.Called(ctx, filter, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOne")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any) error); ok {
		r0 = returnFunc(ctx, filter, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DbInterfaceMock_UpdateOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOne'
type DbInterfaceMock_UpdateOne_Call struct {
	*mock.Call
}

// UpdateOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - update any
func (_e *DbInterfaceMock_Expecter) UpdateOne(ctx any, filter any, update any) *DbInterfaceMock_UpdateOne_Call {
	return &DbInterfaceMock_UpdateOne_Call{Call: _e.mock.On("UpdateOne", ctx, filter, update)}
}

func (_c *DbInterfaceMock_UpdateOne_Call) Run(run func(ctx context.Context, filter any, update any)) *DbInterfaceMock_UpdateOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DbInterfaceMock_UpdateOne_Call) Return(err error) *DbInterfaceMock_UpdateOne_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DbInterfaceMock_UpdateOne_Call) RunAndReturn(run func(ctx context.Context, filter any, update any) error) *DbInterfaceMock_UpdateOne_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type DbInterfaceMock
func (_mock *DbInterfaceMock) Watch(ctx context.Context, pipeline any) (ChangeStreamInterface, error) {
	ret := _mock.Called(ctx, pipeline)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 ChangeStreamInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) (ChangeStreamInterface, error)); ok {
		return returnFunc(ctx, pipeline)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) ChangeStreamInterface); ok {
		r0 = returnFunc(ctx, pipeline)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ChangeStreamInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any) error); ok {
		r1 = returnFunc(ctx, pipeline)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DbInterfaceMock_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type DbInterfaceMock_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - pipeline any
func (_e *DbInterfaceMock_Expecter) Watch(ctx any, pipeline any) *DbInterfaceMock_Watch_Call {
	return &DbInterfaceMock_Watch_Call{Call: _e.mock.On("Watch", ctx, pipeline)}
}

func (_c *DbInterfaceMock_Watch_Call) Run(run func(ctx context.Context, pipeline any)) *DbInterfaceMock_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DbInterfaceMock_Watch_Call) Return(changeStreamInterface ChangeStreamInterface, err error) *DbInterfaceMock_Watch_Call {
	_c.Call.Return(changeStreamInterface, err)
	return _c
}

func (_c *DbInterfaceMock_Watch_Call) RunAndReturn(run func(ctx context.Context, pipeline any) (ChangeStreamInterface, error)) *DbInterfaceMock_Watch_Call {
	_c.Call.Return(run)
	return _c
}
