// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queue

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// NewDbInterfaceMock creates a new instance of DbInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDbInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DbInterfaceMock {
	mock := &DbInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DbInterfaceMock is an autogenerated mock type for the DbInterface type
type DbInterfaceMock struct {
	mock.Mock
}

type DbInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DbInterfaceMock) EXPECT() *DbInterfaceMock_Expecter {
	return &DbInterfaceMock_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type DbInterfaceMock
func (_mock *DbInterfaceMock) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// DbInterfaceMock_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type DbInterfaceMock_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *DbInterfaceMock_Expecter) Context() *DbInterfaceMock_Context_Call {
	return &DbInterfaceMock_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *DbInterfaceMock_Context_Call) Run(run func()) *DbInterfaceMock_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DbInterfaceMock_Context_Call) Return(context1 context.Context) *DbInterfaceMock_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *DbInterfaceMock_Context_Call) RunAndReturn(run func() context.Context) *DbInterfaceMock_Context_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIndexes provides a mock function for the type DbInterfaceMock
func (_mock *DbInterfaceMock) CreateIndexes(index []mongo.IndexModel) error {
	ret := _mock.Called(index)

	if len(ret) == 0 {
		panic("no return value specified for CreateIndexes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]mongo.IndexModel) error); ok {
		r0 = returnFunc(index)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DbInterfaceMock_CreateIndexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIndexes'
type DbInterfaceMock_CreateIndexes_Call struct {
	*mock.Call
}

// CreateIndexes is a helper method to define mock.On call
//   - index []mongo.IndexModel
func (_e *DbInterfaceMock_Expecter) CreateIndexes(index any) *DbInterfaceMock_CreateIndexes_Call {
	return &DbInterfaceMock_CreateIndexes_Call{Call: _e.mock.On("CreateIndexes", index)}
}

func (_c *DbInterfaceMock_CreateIndexes_Call) Run(run func(index []mongo.IndexModel)) *DbInterfaceMock_CreateIndexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []mongo.IndexModel
		if args[0] != nil {
			arg0 = args[0].([]mongo.IndexModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DbInterfaceMock_CreateIndexes_Call) Return(err error) *DbInterfaceMock_CreateIndexes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DbInterfaceMock_CreateIndexes_Call) RunAndReturn(run func(index []mongo.IndexModel) error) *DbInterfaceMock_CreateIndexes_Call {
	_c.Call.Return(run)
	return _c
}

// FindOneAndUpdate provides a mock function for the type DbInterfaceMock
func (_mock *DbInterfaceMock) FindOneAndUpdate(filter interface{}, update interface{}, opts ...options.Lister[options.FindOneAndUpdateOptions]) *mongo.SingleResult {
	// options.Lister[options.FindOneAndUpdateOptions]
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, filter, update)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndUpdate")
	}

	var r0 *mongo.SingleResult
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, ...options.Lister[options.FindOneAndUpdateOptions]) *mongo.SingleResult); ok {
		r0 = returnFunc(filter, update, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.SingleResult)
		}
	}
	return r0
}

// DbInterfaceMock_FindOneAndUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneAndUpdate'
type DbInterfaceMock_FindOneAndUpdate_Call struct {
	*mock.Call
}

// FindOneAndUpdate is a helper method to define mock.On call
//   - filter interface{}
//   - update interface{}
//   - opts ...options.Lister[options.FindOneAndUpdateOptions]
func (_e *DbInterfaceMock_Expecter) FindOneAndUpdate(filter any, update any, opts ...any) *DbInterfaceMock_FindOneAndUpdate_Call {
	return &DbInterfaceMock_FindOneAndUpdate_Call{Call: _e.mock.On("FindOneAndUpdate",
		append([]any{filter, update}, opts...)...)}
}

func (_c *DbInterfaceMock_FindOneAndUpdate_Call) Run(run func(filter interface{}, update interface{}, opts ...options.Lister[options.FindOneAndUpdateOptions])) *DbInterfaceMock_FindOneAndUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []options.Lister[options.FindOneAndUpdateOptions]
		variadicArgs := make([]options.Lister[options.FindOneAndUpdateOptions], len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(options.Lister[options.FindOneAndUpdateOptions])
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DbInterfaceMock_FindOneAndUpdate_Call) Return(singleResult *mongo.SingleResult) *DbInterfaceMock_FindOneAndUpdate_Call {
	_c.Call.Return(singleResult)
	return _c
}

func (_c *DbInterfaceMock_FindOneAndUpdate_Call) RunAndReturn(run func(filter interface{}, update interface{}, opts ...options.Lister[options.FindOneAndUpdateOptions]) *mongo.SingleResult) *DbInterfaceMock_FindOneAndUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOne provides a mock function for the type DbInterfaceMock
func (_mock *DbInterfaceMock) InsertOne(document interface{}) (bson.ObjectID, error) {
	ret := _mock.Called(document)

	if len(ret) == 0 {
		panic("no return value specified for InsertOne")
	}

	var r0 bson.ObjectID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interface{}) (bson.ObjectID, error)); ok {
		return returnFunc(document)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}) bson.ObjectID); ok {
		r0 = returnFunc(document)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bson.ObjectID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = returnFunc(document)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DbInterfaceMock_InsertOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOne'
type DbInterfaceMock_InsertOne_Call struct {
	*mock.Call
}

// InsertOne is a helper method to define mock.On call
//   - document interface{}
func (_e *DbInterfaceMock_Expecter) InsertOne(document any) *DbInterfaceMock_InsertOne_Call {
	return &DbInterfaceMock_InsertOne_Call{Call: _e.mock.On("InsertOne", document)}
}

func (_c *DbInterfaceMock_InsertOne_Call) Run(run func(document interface{})) *DbInterfaceMock_InsertOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DbInterfaceMock_InsertOne_Call) Return(objectID bson.ObjectID, err error) *DbInterfaceMock_InsertOne_Call {
	_c.Call.Return(objectID, err)
	return _c
}

func (_c *DbInterfaceMock_InsertOne_Call) RunAndReturn(run func(document interface{}) (bson.ObjectID, error)) *DbInterfaceMock_InsertOne_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMany provides a mock function for the type DbInterfaceMock
func (_mock *DbInterfaceMock) UpdateMany(filter interface{}, update interface{}) error {
	ret := _mock.Called(filter, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}) error); ok {
		r0 = returnFunc(filter, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DbInterfaceMock_UpdateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMany'
type DbInterfaceMock_UpdateMany_Call struct {
	*mock.Call
}

// UpdateMany is a helper method to define mock.On call
//   - filter interface{}
//   - update interface{}
func (_e *DbInterfaceMock_Expecter) UpdateMany(filter any, update any) *DbInterfaceMock_UpdateMany_Call {
	return &DbInterfaceMock_UpdateMany_Call{Call: _e.mock.On("UpdateMany", filter, update)}
}

func (_c *DbInterfaceMock_UpdateMany_Call) Run(run func(filter interface{}, update interface{})) *DbInterfaceMock_UpdateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DbInterfaceMock_UpdateMany_Call) Return(err error) *DbInterfaceMock_UpdateMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DbInterfaceMock_UpdateMany_Call) RunAndReturn(run func(filter interface{}, update interface{}) error) *DbInterfaceMock_UpdateMany_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOne provides a mock function for the type DbInterfaceMock
func (_mock *DbInterfaceMock) UpdateOne(filter interface{}, update interface{}) error {
	ret := _mock.Called(filter, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOne")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}) error); ok {
		r0 = returnFunc(filter, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DbInterfaceMock_UpdateOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOne'
type DbInterfaceMock_UpdateOne_Call struct {
	*mock.Call
}

// UpdateOne is a helper method to define mock.On call
//   - filter interface{}
//   - update interface{}
func (_e *DbInterfaceMock_Expecter) UpdateOne(filter any, update any) *DbInterfaceMock_UpdateOne_Call {
	return &DbInterfaceMock_UpdateOne_Call{Call: _e.mock.On("UpdateOne", filter, update)}
}

func (_c *DbInterfaceMock_UpdateOne_Call) Run(run func(filter interface{}, update interface{})) *DbInterfaceMock_UpdateOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DbInterfaceMock_UpdateOne_Call) Return(err error) *DbInterfaceMock_UpdateOne_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DbInterfaceMock_UpdateOne_Call) RunAndReturn(run func(filter interface{}, update interface{}) error) *DbInterfaceMock_UpdateOne_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type DbInterfaceMock
func (_mock *DbInterfaceMock) Watch(pipeline interface{}) (ChangeStreamInterface, error) {
	ret := _mock.Called(pipeline)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 ChangeStreamInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interface{}) (ChangeStreamInterface, error)); ok {
		return returnFunc(pipeline)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}) ChangeStreamInterface); ok {
		r0 = returnFunc(pipeline)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ChangeStreamInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = returnFunc(pipeline)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DbInterfaceMock_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type DbInterfaceMock_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - pipeline interface{}
func (_e *DbInterfaceMock_Expecter) Watch(pipeline any) *DbInterfaceMock_Watch_Call {
	return &DbInterfaceMock_Watch_Call{Call: _e.mock.On("Watch", pipeline)}
}

func (_c *DbInterfaceMock_Watch_Call) Run(run func(pipeline interface{})) *DbInterfaceMock_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DbInterfaceMock_Watch_Call) Return(changeStreamInterface ChangeStreamInterface, err error) *DbInterfaceMock_Watch_Call {
	_c.Call.Return(changeStreamInterface, err)
	return _c
}

func (_c *DbInterfaceMock_Watch_Call) RunAndReturn(run func(pipeline interface{}) (ChangeStreamInterface, error)) *DbInterfaceMock_Watch_Call {
	_c.Call.Return(run)
	return _c
}
